/** Every public route — used by the sitemap generator. Keep in sync with App.jsx. */
export const routes = [
  '/',
  '/vision',
  '/project-updates',
  '/donate',
  '/contact',
  '/brisbane-islamic-centre',
  '/brisbane-islamic-centre/vision',
  '/brisbane-islamic-centre/masjid-complex',
  '/brisbane-islamic-centre/cultural-heritage-centre',
  '/brisbane-islamic-centre/project-status',
  '/brisbane-islamic-centre/project-funding',
  '/brisbane-islamic-centre/honoured-guests',
  '/brisbane-islamic-centre/events',
  '/brisbane-islamic-centre/about',
  '/brisbane-islamic-centre/contact',
  '/sukoon-village',
  '/sukoon-village/vision',
  '/sukoon-village/seniors-living',
  '/sukoon-village/lifestyle-centre',
  '/sukoon-village/project-status',
  '/sukoon-village/childcare-centre',
  '/sukoon-village/contact',
]
